name = input("Enter the name: ")
age = input("Enter the age : ")
email = input("Enter the email: ")
course = input("Enter the course: ")
college = input("Enter the college name : ")

print(name)
print(age)
print(email)
print(course)
print(college)